export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  MANAGER: 'MANAGER',
  AGENT: 'AGENT',
};

export const PERMISSIONS = {
  // Company management
  COMPANY_READ: 'company:read',
  COMPANY_UPDATE: 'company:update',
  COMPANY_DELETE: 'company:delete',

  // User management
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',

  // WhatsApp & Messaging
  WHATSAPP_CONFIG: 'whatsapp:config',
  INBOX_READ: 'inbox:read',
  INBOX_WRITE: 'inbox:write',
  CONTACTS_MANAGE: 'contacts:manage',
  BROADCAST_CREATE: 'broadcast:create',

  // Automations & AI
  BOT_BUILD: 'bot:build',
  AI_MANAGE: 'ai:manage',

  // Analytics & Super Admin
  ANALYTICS_VIEW: 'analytics:view',
  SYSTEM_SETTINGS: 'system:settings',
};

export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.WHATSAPP_CONFIG,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.BROADCAST_CREATE,
    PERMISSIONS.BOT_BUILD,
    PERMISSIONS.AI_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.BROADCAST_CREATE,
    PERMISSIONS.BOT_BUILD,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
    PERMISSIONS.CONTACTS_MANAGE,
  ],
};
